export default {
  currentGuest: "Current Guest",
  bookingDetail: "Booking Detail",
  cancel: "Cancel",
  save: "Save",
  mobile: "Mobile",
  email: "Email",
  country: "Country",
  bookingId: "Booking Id",
  confirmed: "Confirmed",
  channel: "Channel",
  property: "Property",
  checkIn: "Check-in",
  checkOut: "Check-out",
  additionalInformation: "Additional Information",
  arrival: "Arrival",
  departure: "Departure",
  specialRequest: "Special Requests",
  internalNotes: "Internal Notes",
  blockProperty: "Block Property",
  startDate: "Start Date",
  endDate: "End Date",
  unBlockProperty: "UnBlock Property",
  paymentType: "Payment type",
  cardholderName: "Cardholder name",
  cardType: "Card Type",
  code: "Code",
  cardNumber: "Card Number",
  expiryDate: "Expiry Date",
  tax: "Tax",
  channelDetails: "Channel details"
};
