export const FETCH_PROPERTY_DATA = "FETCH_PROPERTY_DATA";
export const SAVE_CURRENT_TIMESTAMP = "SAVE_CURRENT_TIMESTAMP";
export const SAVE_CURRENT_UNITS = "SAVE_CURRENT_UNITS";
export const SAVE_EVENTS = "SAVE_EVENTS";
